navio_admin:
    resource: "@NavioAdminBundle/Controller/"
    type:     annotation
    prefix:   /

practice_unite_reference:
    resource: "@PracticeUniteReferenceBundle/Resources/config/routing.yml"
    prefix:   /

navio_engagement:
    resource: "@NavioEngagementBundle/Controller/"
    type:     annotation
    prefix:   /

navio_public:
    resource: "@NavioPublicBundle/Controller/"
    type:     annotation
    prefix:   /

navio_reporting:
    resource: "@ReportingBundle/Controller/"
    type:     annotation
    prefix:   /


navio_service_recovery:
    resource: "@ServiceRecoveryBundle/Controller/"
    type:     annotation
    prefix:   /

navio_workflow:
    resource: "@WorkflowBundle/Controller/"
    type:     annotation
    prefix:   /

navio_o_auth:
    resource: "@NavioOAuthBundle/Controller/"
    type:     annotation
    prefix:   /

#navio_core_core:
#    resource: "@NavioCoreCoreBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#practice_unite_core:
#    resource: "@PracticeUniteCoreBundle/Controller/"
#    type:     annotation
#    prefix:   /

consult:
    resource: "@ConsultBundle/Controller/"
    type:     annotation
    prefix:   /

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /

navio_registry:
    resource: "@NavioRegistryBundle/Controller/"
    type:     annotation
    prefix:   /

navio_framework:
    resource: "@NavioFrameworkBundle/Controller/"
    type:     annotation
    prefix:   /


user_home:
    path: /home
    defaults: { _controller:HospitalBundle:User:home }

home:
    path: /
    defaults: { _controller:HospitalBundle:User:home }

sync:
    resource: "@SyncBundle/Controller/"
    type:     annotation
    prefix:   /

hospital:
    resource: "@HospitalBundle/Controller/"
    type:     annotation
    prefix:   /

samlbundle:
    resource: "@SAMLBundle/Controller/"
    type:     annotation
    prefix:   /

message:
    resource: "@MessageBundle/Controller/"
    type: annotation
    prefix: /

user:
    resource: "@HospitalBundle/Controller/"
    type:     annotation
    prefix:   /

public:
    resource: "@PublicBundle/Controller/"
    type: annotation
    prefix:   /

users:
    resource: "@HospitalBundle/Resources/config/routing.yml"


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_message:
  #  resource: "@FOSMessageBundle/Resources/config/routing.xml"
  # prefix: /pm
user_register:
    path: /register
    defaults: { _controller:HospitalBundle:Registration:register }


# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#acme_oauth_server_auth_login:
#    pattern:  /oauth/v2/auth_login
#    defaults: { _controller: AcmeDemoBundle:Security:login }
#
#acme_oauth_server_auth_login_check:
#    pattern:  /oauth/v2/auth_login_check
#    defaults: { _controller: AcmeDemoBundle:Security:loginCheck }


# NEW MODULE ROUTES [THESE WILL BE RE-FACTORED ALONG THE WAY]
#on_call:
#    resource: "@PracticeUniteOnCallBundle/Controller/"
#    type:     annotation
#    prefix:   /

imag_ldap:
  resource: "@IMAGLdapBundle/Resources/config/routing.yml"

imag_controller:
    resource: "@IMAGLdapBundle/Controller/"
    type:     annotation
#    prefix:   /

# app/config/routing.yml
lightsaml_sp:
    resource: "@SAMLBundle/Resources/config/routing.yml"
    prefix: saml

# Overriding default paths for separate fos login firewall.
fos_user_security_login:
    path:      /account/login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_check:
    path:      /account/login_check
    defaults:  { _controller: FOSUserBundle:Security:check, _method: POST }