services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Navio\AdminBundle\:
    resource: '../../src/Navio/AdminBundle/*'
    exclude: '../../src/Navio/AdminBundle/{Entity,Repository,Model}'

  Navio\AdminBundle\Controller\:
    resource: '../../src/Navio/AdminBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  Navio\EventListeners\Doctrine\TaskChangedNotifier:
    tags:
        -
          name: 'doctrine.orm.entity_listener'
          event: 'postUpdate'
          entity: 'Navio\HospitalBundle\Entity\Task'
          lazy: true